title: Loman Love Tour
description: > # this means to ignore newlines until "baseurl:"
  Becca and Dan's Wedding Tour!
baseurl: "" # the subpath of your site, e.g. /blog
url: "Your-Link.github.io" # the base hostname & protocol for your site # FIXME
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../css/site_style/img/icon-large.png"

include: ['_site_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty
