title: Loman Love Tour
description: Becca and Dan's Wedding Tour!
baseurl: "" # the subpath of your site, e.g. /blog FIXME
url: "Your-Link.github.io" # the base hostname & protocol for your site # FIXME
# Build settings
markdown: kramdown

logo: "../css/site_style/img/icon-large.png" # FIXME

include: ['_site_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty
